# Generated by Django 3.2.3 on 2021-10-10 18:48

import ShopCons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.PositiveIntegerField(null=True)),
                ('consId', models.PositiveIntegerField(null=True)),
                ('shopName', models.CharField(max_length=200, null=True)),
                ('consName', models.CharField(max_length=200, null=True)),
                ('admitDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/ShopkeeperProfilePic/')),
                ('shpadhaar_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/ShopkeeperAdhaar/')),
                ('shopname', models.CharField(max_length=200)),
                ('shopaddr', models.CharField(max_length=200)),
                ('shoptype', models.CharField(choices=[('General Store', 'General Store'), ('Medical Store', 'Medical Store'), ('Chicken Shop', 'Chicken Shop'), ('Mutton Shop', 'Mutton Shop'), ('Cake Shop', 'Cake Shop'), ('Bakery', 'Bakery')], default='General Store', max_length=200)),
                ('mobilenum', models.IntegerField(null=True, validators=[ShopCons.models.validate_mob])),
                ('adhaarnum', models.IntegerField(null=True, validators=[ShopCons.models.validate_adhaar])),
                ('gstnum', models.IntegerField(null=True, validators=[ShopCons.models.validate_gst])),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/ConsumerProfilePic/')),
                ('conadhaar_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/ConsumerAdhaar/')),
                ('address', models.CharField(max_length=200)),
                ('mobilenum', models.IntegerField(null=True, validators=[ShopCons.models.validate_mob])),
                ('adhaarnum', models.IntegerField(null=True, validators=[ShopCons.models.validate_adhaar])),
                ('assignedShopId', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
