# Generated by Django 3.2.3 on 2021-10-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopCons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='assignedShopId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
